config/routes.rb
Rails.application.routes.draw do
  resources :tile_groups
  resources :tiles
  root 'landing#default'

  namespace :public do
  end

  namespace :api do
    get '/dqe', to: 'dqe#hack'
    get '/address', to: 'address#search'

    resource :tiles, only: [:index, :delete]

    get '/tile', to: 'tiles#search'
    post '/tiles/csv', to: 'tiles#csv'
    post '/tile_groups/csv', to: 'tile_groups#csv'
  end
end

app/models/tile.rb
class Tile < ApplicationRecord
  self.primary_key = :id

  belongs_to :tile_group, foreign_key: 'idk'

  include InseeConcern

  scope :containing, -> (point) { where("tiles.shape && ?", point) }

  before_save do
    compute_coordinates
    compute_shape
  end

  def compute_coordinates
    # CRS3035RES200mN2030000E4254200
    size, y_min, x_min = self.idINSPIRE.scan(/CRS3035RES(\d+)mN(\d+)E(\d+)$/).first

    self.longitude_min, self.latitude_min = InseeConcern.laea2degree(x_min, y_min)
    self.longitude_max, self.latitude_max = InseeConcern.translate(self.longitude_min, self.latitude_min, size, size)
  end

  def compute_shape
    factory = RGeo::Geographic.spherical_factory(srid: 4326)

    top_right   = factory.point(self.longitude_max, self.latitude_max)
    bottom_right = factory.point(self.longitude_max, self.latitude_min)
    bottom_left = factory.point(self.longitude_min, self.latitude_min)
    top_left   = factory.point(self.longitude_min, self.latitude_max)

    lines = factory.line_string([top_right, bottom_right, bottom_left, top_left])

    self.shape = factory.polygon(lines)

    pp self
  end
end

app/controllers/api/tiles_controller.rb
require 'csv'


class Api::TilesController < ApplicationController
  before_action :params_query, only: [:search]
  before_action :set_tile, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:csv]

  def search
=begin
    tile = Tile
               .where('longitude_min <= ?', params[:longitude])
               .where('? < longitude_max', params[:longitude])
               .where('latitude_min <= ?', params[:latitude])
               .where('? < latitude_max', params[:latitude])
               .first
=end

    factory = RGeo::Geographic.spherical_factory(srid: 4326)
    point   = factory.point(params[:longitude], params[:latitude])

    tile = Tile.containing(point).first

    if tile.nil?
      render json: {}
    else
      tile_group = tile.tile_group

      population_total_from65to74yearsold = tile_group.ind_age7 - tile_group.ind_age8 # 75+
      population_total_from25to64yearsold = tile_group.ind_age6 - tile_group.ind_age7 # 65+
      population_total_from18to24yearsold = tile_group.ind_r - # all
        tile_group.ind_age6 - # 25+
        tile_group.ind_age5 - # 15-17
        tile_group.ind_age4 - # 11-14
        tile_group.ind_age3 - # 6-10
        tile_group.ind_age2 - # 4-5
        tile_group.ind_age1   # 0-3

      # https://www.insee.fr/fr/statistiques/2520034#dictionnaire

      render json: {
          id:  tile.id,
          population: tile.ind_c,
          household_number: tile_group.men,
          household_surface: tile_group.men_surf,
          household_number_since5years: tile_group.men_occ5,
          household_number_inblock: tile_group.men_coll,
          household_number_greaterthan5persons: tile_group.men_5ind,
          household_number_is1person: tile_group.men_1ind,
          has_household_number_is1person: tile_group.i_1ind.to_i,
          household_number_owner: tile_group.men_prop,
          has_household_number_owner: tile_group.i_prop.to_i,
          household_number_poor: tile_group.men_basr,
          has_household_number_poor: tile_group.i_basr.to_i,
          population_total: tile_group.ind_r,
          population_total_from0to3yearsold: tile_group.ind_age1,
          population_total_from4to5yearsold: tile_group.ind_age2,
          population_total_from6to10yearsold: tile_group.ind_age3,
          population_total_from11to14yearsold: tile_group.ind_age4,
          population_total_from15to17yearsold: tile_group.ind_age5,
          population_total_from18to24yearsold: population_total_from18to24yearsold,
          population_total_from25to64yearsold: population_total_from25to64yearsold,
          population_total_from65to74yearsold: population_total_from65to74yearsold,
          population_total_greaterthan75yearsold: tile_group.ind_age8,
          has_population_total_from65to74yearsold: tile_group.i_age7.to_i,
          has_population_total_greaterthan75yearsold: tile_group.i_age8.to_i,
          earnings_total: tile_group.ind_srf,

          shape: {
              longitude_min: tile.longitude_min,
              longitude_max: tile.longitude_max,
              latitude_min: tile.latitude_min,
              latitude_max: tile.latitude_max,
          }
      }
    end
  end

  def csv
    params.require(:csv)

    csv_file = params[:csv]
    counter = 0

    Tile.transaction do
      CSV.foreach(csv_file.path, headers: true) do |row|
        Tile.create!(row.to_hash)

        counter += 1
        puts counter
      end
    end

    render json: {
        counter: counter,
    }
  end

  # GET /tiles
  # GET /tiles.json
  def index
    @tiles = Tile.all
  end

  # GET /tiles/1
  # GET /tiles/1.json
  def show
  end

  # GET /tiles/new
  def new
    @tile = Tile.new
  end

  # GET /tiles/1/edit
  def edit
  end

  # POST /tiles
  # POST /tiles.json
  def create
    @tile = Tile.new(tile_params)

    respond_to do |format|
      if @tile.save
        format.html { redirect_to @tile, notice: 'Tile was successfully created.' }
        format.json { render :show, status: :created, location: @tile }
      else
        format.html { render :new }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiles/1
  # PATCH/PUT /tiles/1.json
  def update
    respond_to do |format|
      if @tile.update(tile_params)
        format.html { redirect_to @tile, notice: 'Tile was successfully updated.' }
        format.json { render :show, status: :ok, location: @tile }
      else
        format.html { render :edit }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiles/1
  # DELETE /tiles/1.json
  def destroy
    @tile.destroy
    respond_to do |format|
      format.html { redirect_to tiles_url, notice: 'Tile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tile
      @tile = Tile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tile_params
      params.require(:tile).permit(:id, :idINSPIRE, :idk, :ind_c, :nbcar)
    end

    def params_query
      if params[:longitude].nil?
        render json: {error: "invalid parameters"}, status: 400
      end

      if params[:latitude].nil?
        render json: {error: "invalid parameters"}, status: 400
      end
    end
end

app/helpers/tiles_helper.rb
module TilesHelper
end

app/views/tiles/_form.html.erb
<%= simple_form_for(@tile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :id %>
    <%= f.input :idINSPIRE %>
    <%= f.input :idk %>
    <%= f.input :ind_c %>
    <%= f.input :nbcar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tiles/edit.html.erb
<h1>Editing Tile</h1>

<%= render 'form', tile: @tile %>

<%= link_to 'Show', @tile %> |
<%= link_to 'Back', tiles_path %>

app/views/tiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tiles</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Idinspire</th>
      <th>Idk</th>
      <th>Ind c</th>
      <th>Nbcar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tiles.each do |tile| %>
      <tr>
        <td><%= tile.id %></td>
        <td><%= tile.idINSPIRE %></td>
        <td><%= tile.idk %></td>
        <td><%= tile.ind_c %></td>
        <td><%= tile.nbcar %></td>
        <td><%= link_to 'Show', tile %></td>
        <td><%= link_to 'Edit', edit_tile_path(tile) %></td>
        <td><%= link_to 'Destroy', tile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tile', new_tile_path %>

app/views/tiles/new.html.erb
<h1>New Tile</h1>

<%= render 'form', tile: @tile %>

<%= link_to 'Back', tiles_path %>

app/views/tiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @tile.id %>
</p>

<p>
  <strong>Idinspire:</strong>
  <%= @tile.idINSPIRE %>
</p>

<p>
  <strong>Idk:</strong>
  <%= @tile.idk %>
</p>

<p>
  <strong>Ind c:</strong>
  <%= @tile.ind_c %>
</p>

<p>
  <strong>Nbcar:</strong>
  <%= @tile.nbcar %>
</p>

<%= link_to 'Edit', edit_tile_path(@tile) %> |
<%= link_to 'Back', tiles_path %>