config/routes.rb
Rails.application.routes.draw do
  resources :tile_groups
  resources :tiles
  root 'landing#default'

  namespace :public do
  end

  namespace :api do
    get '/dqe', to: 'dqe#hack'
    get '/address', to: 'address#search'

    resource :tiles, only: [:index, :delete]

    get '/tile', to: 'tiles#search'
    post '/tiles/csv', to: 'tiles#csv'
    post '/tile_groups/csv', to: 'tile_groups#csv'
  end
end

app/models/tile_group.rb
class TileGroup < ApplicationRecord
  self.primary_key = :idk

  has_many :tile, foreign_key: 'idk'
end

app/controllers/api/tile_groups_controller.rb
require 'csv'


class Api::TileGroupsController < ApplicationController
  before_action :set_tile_group, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:csv]

  def csv
    params.require(:csv)

    csv_file = params[:csv]
    counter = 0

    TileGroup.transaction do
      CSV.foreach(csv_file.path, headers: true) do |row|
        TileGroup.create!(row.to_hash)

        counter += 1
        puts counter
      end
    end

    render json: {
        counter: counter,
    }
  end

  # GET /tile_groups
  # GET /tile_groups.json
  def index
    @tile_groups = TileGroup.all
  end

  # GET /tile_groups/1
  # GET /tile_groups/1.json
  def show
  end

  # GET /tile_groups/new
  def new
    @tile_group = TileGroup.new
  end

  # GET /tile_groups/1/edit
  def edit
  end

  # POST /tile_groups
  # POST /tile_groups.json
  def create
    @tile_group = TileGroup.new(tile_group_params)

    respond_to do |format|
      if @tile_group.save
        format.html { redirect_to @tile_group, notice: 'Tile group was successfully created.' }
        format.json { render :show, status: :created, location: @tile_group }
      else
        format.html { render :new }
        format.json { render json: @tile_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tile_groups/1
  # PATCH/PUT /tile_groups/1.json
  def update
    respond_to do |format|
      if @tile_group.update(tile_group_params)
        format.html { redirect_to @tile_group, notice: 'Tile group was successfully updated.' }
        format.json { render :show, status: :ok, location: @tile_group }
      else
        format.html { render :edit }
        format.json { render json: @tile_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tile_groups/1
  # DELETE /tile_groups/1.json
  def destroy
    @tile_group.destroy
    respond_to do |format|
      format.html { redirect_to tile_groups_url, notice: 'Tile group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tile_group
      @tile_group = TileGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tile_group_params
      params.require(:tile_group).permit(:idk, :men, :men_surf, :men_occ5, :men_coll, :men_5ind, :men_1ind, :i_1ind, :men_prop, :i_prop, :men_basr, :i_basr, :ind_r, :ind_age1, :ind_age2, :ind_age3, :ind_age4, :ind_age5, :ind_age6, :ind_age7, :i_age7, :ind_age8, :i_age8, :ind_srf, :nbcar)
    end

    def params_query
      if params[:q].nil?
        render json: {error: "invalid parameters"}, status: 400
      end
    end
end

app/helpers/tile_groups_helper.rb
module TileGroupsHelper
end

app/views/tile_groups/_form.html.erb
<%= simple_form_for(@tile_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :idk %>
    <%= f.input :men %>
    <%= f.input :men_surf %>
    <%= f.input :men_occ5 %>
    <%= f.input :men_coll %>
    <%= f.input :men_5ind %>
    <%= f.input :men_1ind %>
    <%= f.input :i_1ind %>
    <%= f.input :men_prop %>
    <%= f.input :i_prop %>
    <%= f.input :men_basr %>
    <%= f.input :i_basr %>
    <%= f.input :ind_r %>
    <%= f.input :ind_age1 %>
    <%= f.input :ind_age2 %>
    <%= f.input :ind_age3 %>
    <%= f.input :ind_age4 %>
    <%= f.input :ind_age5 %>
    <%= f.input :ind_age6 %>
    <%= f.input :ind_age7 %>
    <%= f.input :i_age7 %>
    <%= f.input :ind_age8 %>
    <%= f.input :i_age8 %>
    <%= f.input :ind_srf %>
    <%= f.input :nbcar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tile_groups/edit.html.erb
<h1>Editing Tile Group</h1>

<%= render 'form', tile_group: @tile_group %>

<%= link_to 'Show', @tile_group %> |
<%= link_to 'Back', tile_groups_path %>

app/views/tile_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tile Groups</h1>

<table>
  <thead>
    <tr>
      <th>Idk</th>
      <th>Men</th>
      <th>Men surf</th>
      <th>Men occ5</th>
      <th>Men coll</th>
      <th>Men 5ind</th>
      <th>Men 1ind</th>
      <th>I 1ind</th>
      <th>Men prop</th>
      <th>I prop</th>
      <th>Men basr</th>
      <th>I basr</th>
      <th>Ind r</th>
      <th>Ind age1</th>
      <th>Ind age2</th>
      <th>Ind age3</th>
      <th>Ind age4</th>
      <th>Ind age5</th>
      <th>Ind age6</th>
      <th>Ind age7</th>
      <th>I age7</th>
      <th>Ind age8</th>
      <th>I age8</th>
      <th>Ind srf</th>
      <th>Nbcar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tile_groups.each do |tile_group| %>
      <tr>
        <td><%= tile_group.idk %></td>
        <td><%= tile_group.men %></td>
        <td><%= tile_group.men_surf %></td>
        <td><%= tile_group.men_occ5 %></td>
        <td><%= tile_group.men_coll %></td>
        <td><%= tile_group.men_5ind %></td>
        <td><%= tile_group.men_1ind %></td>
        <td><%= tile_group.i_1ind %></td>
        <td><%= tile_group.men_prop %></td>
        <td><%= tile_group.i_prop %></td>
        <td><%= tile_group.men_basr %></td>
        <td><%= tile_group.i_basr %></td>
        <td><%= tile_group.ind_r %></td>
        <td><%= tile_group.ind_age1 %></td>
        <td><%= tile_group.ind_age2 %></td>
        <td><%= tile_group.ind_age3 %></td>
        <td><%= tile_group.ind_age4 %></td>
        <td><%= tile_group.ind_age5 %></td>
        <td><%= tile_group.ind_age6 %></td>
        <td><%= tile_group.ind_age7 %></td>
        <td><%= tile_group.i_age7 %></td>
        <td><%= tile_group.ind_age8 %></td>
        <td><%= tile_group.i_age8 %></td>
        <td><%= tile_group.ind_srf %></td>
        <td><%= tile_group.nbcar %></td>
        <td><%= link_to 'Show', tile_group %></td>
        <td><%= link_to 'Edit', edit_tile_group_path(tile_group) %></td>
        <td><%= link_to 'Destroy', tile_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tile Group', new_tile_group_path %>

app/views/tile_groups/new.html.erb
<h1>New Tile Group</h1>

<%= render 'form', tile_group: @tile_group %>

<%= link_to 'Back', tile_groups_path %>

app/views/tile_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idk:</strong>
  <%= @tile_group.idk %>
</p>

<p>
  <strong>Men:</strong>
  <%= @tile_group.men %>
</p>

<p>
  <strong>Men surf:</strong>
  <%= @tile_group.men_surf %>
</p>

<p>
  <strong>Men occ5:</strong>
  <%= @tile_group.men_occ5 %>
</p>

<p>
  <strong>Men coll:</strong>
  <%= @tile_group.men_coll %>
</p>

<p>
  <strong>Men 5ind:</strong>
  <%= @tile_group.men_5ind %>
</p>

<p>
  <strong>Men 1ind:</strong>
  <%= @tile_group.men_1ind %>
</p>

<p>
  <strong>I 1ind:</strong>
  <%= @tile_group.i_1ind %>
</p>

<p>
  <strong>Men prop:</strong>
  <%= @tile_group.men_prop %>
</p>

<p>
  <strong>I prop:</strong>
  <%= @tile_group.i_prop %>
</p>

<p>
  <strong>Men basr:</strong>
  <%= @tile_group.men_basr %>
</p>

<p>
  <strong>I basr:</strong>
  <%= @tile_group.i_basr %>
</p>

<p>
  <strong>Ind r:</strong>
  <%= @tile_group.ind_r %>
</p>

<p>
  <strong>Ind age1:</strong>
  <%= @tile_group.ind_age1 %>
</p>

<p>
  <strong>Ind age2:</strong>
  <%= @tile_group.ind_age2 %>
</p>

<p>
  <strong>Ind age3:</strong>
  <%= @tile_group.ind_age3 %>
</p>

<p>
  <strong>Ind age4:</strong>
  <%= @tile_group.ind_age4 %>
</p>

<p>
  <strong>Ind age5:</strong>
  <%= @tile_group.ind_age5 %>
</p>

<p>
  <strong>Ind age6:</strong>
  <%= @tile_group.ind_age6 %>
</p>

<p>
  <strong>Ind age7:</strong>
  <%= @tile_group.ind_age7 %>
</p>

<p>
  <strong>I age7:</strong>
  <%= @tile_group.i_age7 %>
</p>

<p>
  <strong>Ind age8:</strong>
  <%= @tile_group.ind_age8 %>
</p>

<p>
  <strong>I age8:</strong>
  <%= @tile_group.i_age8 %>
</p>

<p>
  <strong>Ind srf:</strong>
  <%= @tile_group.ind_srf %>
</p>

<p>
  <strong>Nbcar:</strong>
  <%= @tile_group.nbcar %>
</p>

<%= link_to 'Edit', edit_tile_group_path(@tile_group) %> |
<%= link_to 'Back', tile_groups_path %>